source 'https://rubygems.org'

gem 'puppet', '~> 8.0'
gem 'rspec-puppet', '~> 4.0'
gem 'puppet-lint', '~> 4.0'
gem 'puppetlabs_spec_helper', '~> 7.0'
gem 'puppet-syntax', '~> 4.0'
gem 'metadata-json-lint', '~> 4.0'
