require 'puppetlabs_spec_helper/rake_tasks'
require 'puppet-lint/tasks/puppet-lint'
require 'puppet-syntax/tasks/puppet-syntax'

PuppetLint.configuration.send('disable_autoloader_layout')
PuppetLint.configuration.send('disable_documentation')
PuppetLint.configuration.relative = true

PuppetSyntax.manifests_paths = ['site-modules/**/manifests/**/*.pp']
PuppetSyntax.hieradata_paths = ['data/**/*.yaml']
